name: Deploy to Azure App Service

on:
  push:
    branches:
      - main # Replace with your branch name if different

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install Dependencies
      run: dotnet restore

    - name: Build Application
      run: dotnet build --configuration Release

    - name: Publish Application
      run: dotnet publish -c Release -o publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testappcicd' # Replace with your app service name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: publish
